spring:
  application:
    name: dingzi-ai-agent
  profiles:
    active: local
#  datasource:
#    mysql:
#      driver-class-name: com.mysql.cj.jdbc.Driver
#      url:
#      username:
#      password:
#    postgresql:
#      driver-class-name: org.postgresql.Driver
#      url:
#      username:
#      password:

  # 添加此配置是为了通过 Mybatis 依赖的编译, 项目中暂不会用到此数据库连接
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql:///db
    username: xxxx
    password: xxxx


  ai:
    # AI LLM
    dashscope:
      api-key: your-api-key
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      chat:
        options:
          model: qwen3-max
      # embedding model
      embedding:
        base-url: https://dashscope.aliyuncs.com
        options:
          model: text-embedding-v1
    # vector store
    vectorstore:
      pgvector:
        index-type: HNSW
        distance-type: COSINE_DISTANCE
        dimensions: 1536
        max-document-batch-size: 10000 # Optional: Maximum number of documents per batch
        initialize-schema: true
    # MCP
    # stdio
#    mcp:
#      client:
#        stdio:
#          servers-configuration: classpath:mcp-servers.json
    # sse
#    mcp:
#      client:
#        sse:
#          connections:
#            server1:
#              url: http://localhost:9527
server:
  port: 8100
  servlet:
    context-path: /api

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.dingzk.dingziaiagent.controller
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn
mybatis-plus:
  configuration:
#  # SQL 日志调试
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1

# SearchAPI apiKey
search-api:
  apiKey: your-api-key

